name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          src: "./src"
          version: 0.2.2
          args: check --format --fix
      - uses: chartboost/ruff-action@v1
